### PR TITLE
not push new branch for PR from forked repository

### PR DESCRIPTION
**Pull request by himorin**
as title.

(note, as test, PR is made from forked repository)

### CODE REVIEW

**Comment by himorin** [comment]
```
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/reference/issues#create-an-issue-comment'
    }
```
it seems adding comment is not allowed for this pattern, neither...

**Comment by himorin** [comment]
@nigelmegitt I assume this is what I've proposed (in DM).

**Review by nigelmegitt — APPROVED** [review]
Seems to work, but I can't easily check it doesn't break PRs opened against the w3c repo. Anyway at least with this specific PR I can see that the checks pass without the push error, which is a good step forward.

**Comment by himorin** [comment]
> Seems to work, but I can't easily check it doesn't break PRs opened against the w3c repo. Anyway at least with this specific PR I can see that the checks pass without the push error, which is a good step forward.

Yeah, that is the point which I cannot verify with this PR / check passed.
This PR does add some non-applicable criteria, but does not add any criteria to fail, so I believe there should no additional break (but may add possible false negative of checker...).

Let me merge this, and check with one PR just for check (no intended to be merged)?

**Comment by nigelmegitt** [comment]
> Let me merge this, and check with one PR just for check (no intended to be merged)?

Please go ahead.

**Comment by himorin** [comment]
Yes. I'll add PRs for testing.

**Pull request merged**
