### PR TITLE
fix radii example

### PR DESCRIPTION
**Pull request by MarcAntoine-Arnaud**

### CODE REVIEW

**Review by cconcolato — APPROVED** [review]
Thank you!

**Comment by MarcAntoine-Arnaud** [comment]
@cconcolato what can be fixed to pass checks ?

**Comment by cconcolato** [comment]
> @cconcolato what can be fixed to pass checks ?

There are 2 failures:
- One is the IPR rule because you are not a WG member. I don't know if it can be overridden. It should because your PR is not bringing any IP at all. 
- The other one seems a pure GitHub issue.

@himorin can you have a look?

**Comment by MarcAntoine-Arnaud** [comment]
I have submit this afternoon to be member of the WG. If it can help!

**Comment by nigelmegitt** [comment]
I think there's at least a strong chance that the PR build failure is because the PR branch is from a fork. I will try it from an in-repo branch and see if it succeeds.

**Comment by himorin** [comment]
> I think there's at least a strong chance that the PR build failure is because the PR branch is from a fork. I will try it from an in-repo branch and see if it succeeds.

Ah,, could be. I need to check in deep of current GHAction, but such issue could happen since current script just uses git push to create preview branch (= github deploy key mismatch)..

**Comment by nigelmegitt** [comment]
Opened #1251 from a branch created in the repo, which just imports @MarcAntoine-Arnaud 's commit and passes all the tests. Closing this in favour of that. I think the way I've done this does not remove the log showing that this is @MarcAntoine-Arnaud 's contribution, for which, thank you!

**Comment by nigelmegitt** [comment]
Just to follow up, #1251 merged, which incorporates this change @MarcAntoine-Arnaud. Thank you again!

**Pull request closed without merging**
