### PR TITLE
Clean up and refactor features (#688, #763, #789, #790, #791, #792, #…

### LINKED ISSUE #688: Exclude #rubyAlign-withBase from #rubyAlign.
`tts:rubyAlign-withBase` attribute does not exist

It is also not clear if `#rubyAlign` includes support for the value `withBase`

Suggest that `#rubyAlign` exclude support for value `withBase`

### LINKED ISSUE #763: Rewrite version 1 features as references to [TTML1].
In order to avoid potential ambiguity, rewrite all version 1 feature designator descriptions by making direct reference to their definitions in [TTML1].

### LINKED ISSUE #789: Add missing constraints on content profile feature prohibitions.
In the definition of feature designators (E.1), need to make consistent use of language makes it an error for a content profile to require or permit a feature but prohibit a feature upon which the former feature depends (or implies).

### LINKED ISSUE #790: Refactor #condition features.
The current definition of `#condition` related features is quite awkward, and needs refactored as:

`#condition-no-media` = condition expressions without media() function
`#condition-media` = condition expressions with media() function
`#condition` = `#condition-no-media` + `#condition-media`

### LINKED ISSUE #791: Add missing #display-version-2 feature.

### LINKED ISSUE #792: Remove #font*-p feature designators.
See also #785.

### LINKED ISSUE #793: Refactor #rubyAlign features.
The current definition of `#rubyAlign` related features is quite awkward, and needs refactored as:

`#rubyAlign-no-withBase` = ruby align values except `withBase`
`#rubyAlign-withBase` = ruby align value `withBase`
`#rubyAlign` = `#rubyAlign-no-withBase` + `#rubyAlign-withBase`

See also

### PR DESCRIPTION
**Pull request by skynavga**
…793).

Closes #688.
Closes #763.
Closes #789.
Closes #790.
Closes #791.
Closes #792.
Closes #793.

Manual merge will be required to bring the following merged content up to date with this PR:
- #729

Addresses #710 in part by restating definition of `#origin` by reference to TTML1 definition.

### CODE REVIEW

**Comment by skynavga** [comment]
@nigelmegitt Per the suggestion by @palemieux (https://github.com/w3c/ttml2/pull/794#pullrequestreview-123585375), I would like to merge this early with approval of the WG during this coming Thursday's call.

**Comment by skynavga** [comment]
@nigelmegitt regarding https://github.com/w3c/ttml2/pull/794#pullrequestreview-124384168, there is no such thing as prohibiting a feature in a processor profile, only a content profile; in a processor profile, if the feature isn't required, then it is optional; if you require support for a superset feature, saying a subset feature is optional is effectively subsumed by the superset feature being required, so it doesn't matter whether the subset feature is marked as required or optional

**Comment by skynavga** [comment]
@nigelmegitt I have attempted to address all your comments in https://github.com/w3c/ttml2/pull/794/commits/ca595f1ae55f7b8ed54c6c9bcbd213bd646e4399.

**Comment by nigelmegitt** [comment]
@skynavga I just spotted that the build did not complete for this pull request, presumably because of the merge conflicts, so I cannot complete my review. For example the latest commit introduces `#animate-minimal` but right now the built version [`#animate`](https://rawgit.com/w3c/ttml2/issue-0763-refactor-v1-features-build/index.html#feature-animate) feature makes no mention of it. Would it be possible to resolve the build conflicts or are there cross-branch dependencies that are making that difficult?

**Comment by nigelmegitt** [comment]
@palemieux this pull request has changed very significantly since your approval. I'm going to dismiss your review, with apologies if you're actually fine with the newer changes - just means you'll need to re-review.

**Comment by skynavga** [comment]
@nigelmegitt merged from master, build is at https://rawgit.com/w3c/ttml2/issue-0763-refactor-v1-features-build/index.html

**Pull request merged**
