### PR TITLE
Clarify text combination semantics in a ruby container context (#978).

### PR DESCRIPTION
**Pull request by skynavga**

### CODE REVIEW

**Comment by skynavga** [comment]
It does not define it because no specification text mentions this possibility even though it is syntactically possible. Therefore, there is no defined behavior. It falls into the same category of early implementers of TTML1 specifying `tts:origin` and `tts:extent` on a `div` or `p`, and inferring that such use was meant to create an anonymous region (or alter an associate, specified region).

**Comment by skynavga** [comment]
@palemieux I disagree; the introduction of a note at this time is appropriate; what is your argument against doing so?

**Comment by palemieux** [comment]
Read he thread in the issue

**Comment by skynavga** [comment]
@palemieux are you disputing the facts stated in the comment? if so, then what is your rationale?

**Comment by skynavga** [comment]
Closing without merging, but marking issue for ttml.next.

**Pull request closed without merging**
