### PR TITLE
Update non-REC CSS links to latest versions, remove CSS Box reference (#1188).

### LINKED ISSUE #1188: Update CSS Writing Mode status and links.
CSS WM Level 3 is now REC [1]. Also check other references for updates.

[1] https://www.w3.org/TR/2019/REC-css-writing-modes-3-20191210/

### PR DESCRIPTION
**Pull request by skynavga**
Closes #1188.

### CODE REVIEW

**Comment by nigelmegitt** [comment]
This fails IPR checks due to admin issues upstream. I'm not marking it as non-substantive because it isn't.

**Comment by skynavga** [comment]
@nigelmegitt I take it that your comment "I'm not marking it as non-substantive because it isn't." should have said "I'm not marking it as substantive because it isn't." and refers to the IPR check issue, yes?

**Comment by nigelmegitt** [comment]
@skynavga no, I was saying that this is a substantive change, but your comment made me look again and I realise now that all the modifications are non-normative, so I will mark as non-substantive after all.

**Comment by nigelmegitt** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by skynavga** [comment]
@nigelmegitt what is "ash-nazg"?

**Comment by nigelmegitt** [comment]
@skynavga that comment was auto-generated by ash-nazg and posted in my name! ash-nazg is the W3 repository management system.

**Pull request merged**
