### PR TITLE
Add customisation options appendix

### LINKED ISSUE #156: Create a section on options for customisation
As per [Action-460](https://www.w3.org/AudioVideo/TT/tracker/actions/460), and recorded in [these minutes](https://www.w3.org/2016/04/07-tt-minutes.html#action01), add a section to TTML2 explaining the options for customisation, including as a minimum:
-  deliberate non-compliance of presentation processors with the specification; 
-  local setting of implementation dependent values such as default value for `tts:color` etc.; 
-  use of parameters and conditions to control styling for using.

This will also serve as a placeholder for any other mechanisms that we introduce for customisation.

### PR DESCRIPTION
**Pull request by nigelmegitt**
Adds a new non-normative appendix describing possible approaches to customisation.

Closes #156.

### CODE REVIEW

**Comment by tairt** [comment]
I will need more time to the usual 3 days to review. Thanks!

**Comment by tairt** [comment]
@nigelmegitt If more review time for a PR is requested, shouldn't this be 10 working days?

**Comment by skynavga** [comment]
Feel free to review and comment and I will address. This was an editorial
only (non-normative) change so I can merge at any time.

**Comment by nigelmegitt** [comment]
@tairt You might not have caught up with the minutes from Thursday's meeting yet. I proposed, and it was agreed that we would merge the open pull requests to create a version of the ED with everything in for review prior to publishing as a WD for wide review by June 30. So your review comments are still very much welcome, and the review can be done in the context of the ED, with any issues found being raised as new issues on this repo please.

**Comment by tairt** [comment]
OK! Thanks @nigelmegitt and @skynavga for the clarification!

**Pull request merged**
