### PR TITLE
Adds support for BT 2100 PQ HDR pixels in PNG

### LINKED ISSUE #244: Signaling HDR pixels in PNG for use with <image>
The TTML2  allow PNG images to be displayed. In order to allow the use of the `image` with HDR video (see #233 for additional background on HDR video), TTML2 should support PNG sources carrying HDR images as specified in the [attached](https://github.com/w3c/ttml2/files/778427/png_st2084_20170125.zip). The latter is intended to be compatible with current PNG implementations and uses existing PNG structures:

- HDR pixels are carried PQ-encoded using full-range quantization
- the profile name field of the iCCP chunk is used to signal the color system
- implementations that do not recognize the magic profile names but
support the iCCP chunk will process the image using an embedded ICC
profile, which can evolve as the ICC standard evolves
- implementations that do not recognize the iCCP chunk should display
the image according to the cHRM and gAMA chunks
- implementations that ignore iCCP, cHRM and gAMA chunks will still
display the image
- implementations that merely blit the PNG onto video with the same
HDR colorspace, but without any color conversion, would end-up with an
adequate image

### PR DESCRIPTION
**Pull request by palemieux**
Closes #244

### CODE REVIEW

**Comment by skynavga** [comment]
Superseded by #285.

**Comment by skynavga** [comment]
Closed this in error.

**Comment by palemieux** [comment]
See https://w3c.github.io/png-hdr-pq/. Recommend closing.

**Comment by skynavga** [comment]
Work will be done in separate WG Note. A new issue may be filed against TTML2 during WR (or against TTML.next) requesting that such a note be referenced.

**Pull request closed without merging**
