### PR TITLE
Fix typos (#678).

### LINKED ISSUE #678: Fix typos.
Need to fix the following typos:

- [x] in Table E-1, ``#background`` should be marked for version 2, not 1;
- [x] in Table E-1, ``#background-image`` should be marked for version 2, not 1;
- [x] in Table E-1, ``#contentProfiles`` should be marked as mandatory, not optional;
- [x] in Table E-1, ``#inferProcessorProfile`` should be marked as mandatory, not optional;
- [x] in Table E-1, ``#permitFeatureNarrowing`` should be marked as mandatory, not optional;
- [x] in Table E-1, ``#permitFeatureWidening`` should be marked as mandatory, not optional;
- [x] in Table E-1, ``#transformation-version-2`` should be marked for version 2, not 1;
- [x] in ``profiles/ttml2-{presentation,transformation}.xml``, ``#core`` should follow ``#contentProfiles``;
- [x] in E.1.161, `tts:rubyAlign-withBase` should be changed to `tts:rubyAlign` and the href fragment id similarly updated.
- [x] update Table E-2 to match what is in Table E-1;
- [x] update Table E-3 to match what is in Table E-1; 

Check off as added to some PR.

### PR DESCRIPTION
**Pull request by skynavga**
Closes #678.

### CODE REVIEW

**Comment by skynavga** [comment]
@cconcolato this is not an optional to mandatory change, it is listed as mandatory in the profiles in Appendix G; this PR is fixing an editorial inconsistency between Table E-1 and Appendix G (where Appendix G is the normative specification and Table E-1 is a summary).

**Comment by nigelmegitt** [comment]
I agree with @cconcolato - if you're going to make this change it should update tables E-2 and E-3 also.

**Comment by skynavga** [comment]
Agreed, I will update E-2 and E-3 as well.

**Comment by skynavga** [comment]
@cconcolato @nigelmegitt addressed your comments (that could be resolved editorially); please check and approve

**Comment by skynavga** [comment]
Partially addressed #688.

**Pull request merged**
