### PR TITLE
Update deploy and build scripts

### LINKED ISSUE #500: Fix up build scripts so Travis build works
As requested by @skynavga , to be based on the recent similar work on the w3c/ttml1 repository.

### PR DESCRIPTION
**Pull request by nigelmegitt**
Matches ttml1 build scripts as closely as possible.

Fixes #500

### CODE REVIEW

**Comment by nigelmegitt** [comment]
Appears to fail only because the deploy key hasn't been created yet - @plehegar will add that.

**Comment by plehegar** [comment]
hum... somehow travis didn't get triggered by my commit...

**Comment by nigelmegitt** [comment]
Travis had been deactivated - I reactivated it for this repo, but still the pr build hasn't run yet.

**Comment by nigelmegitt** [comment]
Confirmed everything now seems to be building okay. The only thing I haven't worked out yet is why we get @@ @@@@ @@@@ instead of the date.

**Comment by nigelmegitt** [comment]
By the way, the built output can be seen at https://rawgit.com/w3c/ttml2/issue-0500-build-and-deploy-build/index.html

**Comment by nigelmegitt** [comment]
Right, I think this is all done - please review @skynavga and/or @palemieux so it can be merged.

**Pull request merged**
