### PR TITLE
Remove usesForced named metadata item

### LINKED ISSUE #609: Loosen coupling between item name="usesForced" and forced.
The "usesForced" named metadata item definition is very tightly coupled with use of `condition` in the document instance, in relation to the `forced` bound parameter. This means it cannot be used in other contexts that may define some forced functionality. See also the thread leading up to https://github.com/w3c/imsc/issues/311#issuecomment-361318848

Additionally, only one scope of usage is defined, at the document level. It would seem a reasonable optional usage to be able to scope it to an element in the body content such as `div` etc.

Since no processing semantic is based on the metadata item, there we can be less prescriptive about its usage. This will also have the effect of reducing the implementation and test burden.

Instead of the current wording:

> A boolean that expresses whether some `<condition>` expression makes use of the `forced` bound parameter, where the value adheres to `xsd:boolean`. If this named metadata item is present in a document instance, then it must be specified as a child of the `head` element.

I propose:

> A boolean that expresses whether some content within the specifying element's scope makes use of forced display semantics, where the value adheres to `xsd:boolean`. If this named metadata item is specified as a child of the `head` element then the applicable scope is the whole document; if specified as a child of a content element, then the applicable scope is that element and its descendants.
> Note:
> Forced display semantics can be expressed by use of the `forced` bound parameter within a `<condition>` expression.

### PR DESCRIPTION
**Pull request by palemieux**
Closes #609 

See https://github.com/w3c/ttml2/pull/611#issuecomment-362032101 and https://github.com/w3c/ttml2/pull/611#issuecomment-362031664

Moots PR #611

### CODE REVIEW

**Comment by cconcolato** [comment]
Built version: http://rawgit.com/w3c/ttml2/issue-0609-remove-usesForced-build/index.html

**Comment by palemieux** [comment]
@skynavga Actually three members of the WG do not believe it serves a use case... so which use case does it serve? Moreover, as far as I can tell, `usesForced` was introduced in https://github.com/w3c/ttml2/commit/4f9fa5cab861c19cb5f1ec63374c85e86f9933e5 , which has no issue tied to it, so I doubt the group discussed it at all.

**Comment by nigelmegitt** [comment]
#### Use case

@skynavga What real use case does it serve? 

Just in case this was mentioned in the requirements document for TTML at https://www.w3.org/TR/2006/NOTE-ttaf1-req-20060427/ I checked this, and it is absent there. (For clarity, I do not believe we are bound by that document in its entirety, and can potentially introduce use cases not considered in that document, but it's fairly comprehensive and has stood the test of time reasonably well; I checked it because if the need for a usesForced metadata item had somehow been represented in that document then the case for keeping it would have been clear.)

#### History of usesForced discussion in the TTWG

A search reveals that after it was introduced initially without discussion, we talked about it very briefly at the TPAC F2F in Lisbon ([minutes](https://lists.w3.org/Archives/Public/public-tt/2016Sep/0040.html)) where the group agreed to keep usesForced on the basis that it is referenced elsewhere in the specification. Even at that time there was evidently a request to remove it.

#### Impact of removal

However, on reviewing this dependency, it seems like it is somewhat arbitrary and the usesForced metadata item name can certainly be removed straightforwardly: there's a reference to it in the `forced` bound parameter that would need to be removed, but there's no further onward impact than that.

**Comment by nigelmegitt** [comment]
Apologies for the mess here in terms of comments - the proper place for the discussion of removal of usesForced is in the issue, so I've copied my above comment to https://github.com/w3c/ttml2/issues/609#issuecomment-362541539; in the meantime the current count is that three members of the WG  are happy to remove it, and one is not.

**Comment by nigelmegitt** [comment]
The issue has been closed, so closing this pull request.

**Pull request closed without merging**
