### PR TITLE
New feature designators for extent (#582).

### LINKED ISSUE #582: Define new feature designator for extent modifications, including measure
TTML1 defines extent based on `<length>`
TTML2 defines extent based on `<extent>`. 
This requires a new feature designator.

I suggest (based on Glenn's input) to define the following:
- `#extent-measure`
- `#extent-image` (extent applies to `image`)
- `#extent-block` (special extent semantics for `div`/`p`)
- `#extent-version-2` as
   - `#extent`
   - `#extent-block`
   - `#extent-image`
   - `#extent-measure`

### PR DESCRIPTION
**Pull request by cconcolato**
closes #582

### CODE REVIEW

**Comment by skynavga** [comment]
@nigelmegitt @palemieux please recheck this with the addition of https://github.com/w3c/ttml2/pull/598/commits/87ddd9063d3e4cce484fda36ec141e060eb340f4

**Comment by skynavga** [comment]
@nigelmegitt as I mention above, ``auto`` is already present in TTML1, so what does #extent-auto mean here? also, why a feature for ``contain`` but no feature for ``cover``? what was specified was inconsistent and confusing; if one is to support ``#extent-version-2`` it seems reasonable that auto, contain, and cover semantics need to be included

**Comment by cconcolato** [comment]
@nigelmegitt I agree with @skynavga. The initial PR was not consistent. Could you change your review?

**Comment by skynavga** [comment]
@nigelmegitt ping

**Pull request merged**
