### PR TITLE
Explicitly mark for the mandatory or optional presence of linear whit…

### LINKED ISSUE #315: LWSP in attribute and value expressions?
I apparently missed the three day window on https://github.com/w3c/ttml2/pull/310.

As I understand it, and please correct me if I am wrong, expressions of the form `rgba(        233,    1,0          )` are now permitted.

If so, this will require TTML1 implementations to be revised and tested, without stated benefits as far as I can tell.

### PR DESCRIPTION
**Pull request by skynavga**
…espace (#315).

Closes #315.

### CODE REVIEW

**Comment by nigelmegitt** [comment]
Built version at https://rawgit.com/w3c/ttml2/issue-0315-lwsp-rules-build/index.html

**Comment by skynavga** [comment]
@nigelmegitt yes, we can do that, but under #587, not #315

**Comment by skynavga** [comment]
@palemieux I expect to merge this tomorrow or the next day unless I see a change requested review; are you ok with this as it stands?

**Comment by skynavga** [comment]
@palemieux No. See ``{r,g,b,a}-value``. I did it a bit differently here so it wouldn't overflow the column width, but it is equivalent to putting inside the rgb/rgba.

**Comment by palemieux** [comment]
Alright. Was `II` used instead of `<lwsp> | <lwsp>` for reasons other than conciseness?

**Comment by skynavga** [comment]
@palemieux what do you mean? I don't follow

**Comment by palemieux** [comment]
@skynavga I mean that `<lwsp>` is explicit in expressions, but around `||` operators where the `<lwsp>` are built-in the definition of the `||`, right? Same for `&&`, although these are not used anywhere as far as I can tell.

**Comment by skynavga** [comment]
@palemieux ``|`` (call this the _CHOOSE1_ operator) and `||` (call this the _CHOOSEN_ operator) are not equivalent; _CHOOSE1_ admits only one choice, while _CHOOSEN_ admits one or more choices, with ``<lwsp>`` separating multiple choices; none of the _CHOOSE1_ constructs specify ``<lwsp>`` at the outer boundary, i.e., just before or after the choice operator; however, _CHOOSEN_ clearly requires ``<lwsp>`` between options;

**Comment by skynavga** [comment]
@palemieux I will remove reference to the ``&&`` rule, since, as you point out, it is not presently used

**Comment by skynavga** [comment]
@palemieux removed ``&&`` rule

**Comment by palemieux** [comment]
@skynavga Got it. Can an option listed by the `||` operator appear more than once? The definition does not prevent it.

**Comment by skynavga** [comment]
@palemieux I would think that duplication of options should not be permitted; however, I find that neither CSS2.1 nor CSS3 prohibits duplicates; however,  I think we should proscribe duplicates, which I will add shortly.

**Comment by skynavga** [comment]
@palemieux proscribed duplication via ``||``

**Comment by nigelmegitt** [comment]
@skynavga If you're going to make significant changes like this please do not merge without giving folk a chance to look. As it happens in this case I think I'm okay with the changes, but they are not just editorial.

**Pull request merged**
