### PR TITLE
Remove xml:base and @condition from chunk (#961).

### LINKED ISSUE #961: Remove xml:base and @condition from chunk.
An `xml:base` attribute was inadvertently defined for use on the `chunk` element. However, the `chunk` element does not permit any child elements or metadata attributes to which an `xml:base` attribute could potentially apply. This is currently reflected in the schemas as well which do not define use of `xml:base`.

### PR DESCRIPTION
**Pull request by skynavga**
Closes #961.

### CODE REVIEW

**Comment by skynavga** [comment]
Defer to ttml.next.

**Comment by skynavga** [comment]
Reopened this PR to remove `@condition` and `xml:base` from `chunk` element.

**Comment by nigelmegitt** [comment]
I think this pull request is somewhat premature - we haven't really discussed the issue yet or what we would like to do about it. Happy to add it to the agenda for Thursday.

**Comment by nigelmegitt** [comment]
Discussed in today's call. Agreement in principle to proceed, with a request for accompanying tests in a PR to w3c/ttml-tests.

**Comment by nigelmegitt** [comment]
Tests at w3c/ttml2-tests#210 look good.

**Pull request merged**
