### PR TITLE
Remove #ruby-non-nested* features since nesting is not permitted by d…

### LINKED ISSUE #476: Remove #ruby-non-nested* features as there is no nesting by definition.
Can someone point the group to timed text use cases for nested ruby annotations?

The current support for nested ruby annotations complicates specification and implementation.

### PR DESCRIPTION
**Pull request by skynavga**
…efinition (#476).

Closes #476.

### CODE REVIEW

**Comment by nigelmegitt** [comment]
Built version available at https://rawgit.com/w3c/ttml2/issue-0476-ruby-nesting-build/index.html

**Comment by skynavga** [comment]
@nigelmegitt thanks; fixed in 4d964c78d799b84b2a9a89343bed641ab843a80c.

**Comment by nigelmegitt** [comment]
(post travis build, still looking good)

**Comment by palemieux** [comment]
Diff at https://services.w3.org/htmldiff?doc1=https%3A%2F%2Frawgit.com%2Fw3c%2Fttml2%2Fgh-pages%2Findex.html&doc2=https%3A%2F%2Frawgit.com%2Fw3c%2Fttml2%2Fissue-0476-ruby-nesting-build%2Findex.html#style-attribute-ruby

**Pull request merged**
